name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Clone Winlator Source
      run: |
        git clone https://github.com/brunodev85/winlator.git winlator_src
        cp -r winlator_src/* .
        rm -rf winlator_src

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Apply Code Injections
      run: |
        chmod +x patch_script.sh
        ./patch_script.sh

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign APK (Optional - using debug key for now)
      run: |
        # If you have a release keystore, you can add signing steps here.
        # For now, we'll use the generated unsigned or debug APK.
        echo "Build finished."

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: winlator-custom-sd845
        path: app/build/outputs/apk/release/*.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
